python main_test.py \
    --image_dir /dataset/iu_xray-finetune/images/ \
    --ann_path /dataset/iu_xray-finetune/annotation.json \
    --dataset_name iu_xray \
    --max_seq_length 60 \
    --threshold 3 \
    --epochs 25 \
    --batch_size 16 \
    --lr_ve 2e-4 \
    --lr_ed 5e-4 \
    --step_size 10 \
    --gamma 0.8 \
    --num_layers 3 \
    --topk 64 \
    --cmm_size 2048 \
    --cmm_dim 512 \
    --seed 7580 \
    --beam_size 3 \
    --save_dir results/iu_xray/ \
    --log_period 50 \
    --optim Adam \
    --model_frame swin_transformer_tiny \
    --device cuda:0 \
    --load /results/best_IU/model_best.pth \
   --topic \
   --retrieval \
   --local_guide \
   --report_topk 30 \
   --concept_num 100 \
   --concept_topk 20 \

